### ISSUE TITLE
New release date

### ISSUE THREAD

**Issue by kepler** [konlpy/konlpy#365] opened 2021-09-02 21:11 UTC
Hello!

Are there any plans to release a new version soon? The dependency of version 0.5.2 on BeautifulSoup is blocking us from using konlpy.

Thanks.

**Comment by combacsa** [comment] 2022-01-02 16:05
Hello, @kepler. `0.6.0` just has been released(4 hours ago) and you'll find the problem with `BeautifulSoup` version dependency is now gone. Could you please check if the problem is resolved? Thanks in advance.

* https://pypi.org/project/konlpy/0.6.0/

**Comment by OrianeN** [comment] 2022-01-03 14:18
Hello @combacsa, I was also blocked by the same issue and I've just tested installing and using `konlpy-0.6.0`, `jpype1-1.3.0` and `beautilfulsoup-4.6.0` with success, both on Windows 10 (Python 3.8.6) and Windows Subsystem for Linux (Ubuntu 20.04, Python 3.8.10) !

Thank you very much for this release !

**Comment by combacsa** [comment] 2022-01-04 17:28
@OrianeN Thank you for sharing your test result! (To be honest, I was another person who was waiting for the new release and made some requests using various channels until last year.)

Waiting for @kepler's response to make sure if we could safely close this issue.

**Comment by kepler** [comment] 2022-01-06 01:05
Thanks a lot, @combacsa!
I'm currently on vacations, so can't really test it out, but feel free to close this issue, considering @OrianeN's feedback. In case I later find any problem, I'll let you know.

**Comment by combacsa** [comment] 2022-01-06 05:29
Thank you @kepler ! Please do not hesitate to reopen this issue or create anothet issue.

**Closed** 2022-01-06 05:29 UTC
